Week two
temiloluwa-hub/portfolio pull request #3
Opened 2021-06-08 22:37 UTC by temiloluwa-hub

Slight Change :/

2021-06-09 16:01 UTC, aljonpineda requested changes
The scorekeeper page doesn't look like it can be accessed. Is this intentional?

2021-06-09 16:01 UTC, aljonpineda commented on portfolio/src/main/webapp/app.js
> +}
Although semicolons aren't required in JavaScript, make sure to add a semicolon at the end of every statement to conform to the [JS style guide](https://google.github.io/styleguide/jsguide.html#formatting-semicolons-are-required). I've marked the places below that are also missing a semicolon.

2021-06-09 16:01 UTC, aljonpineda commented on portfolio/src/main/webapp/app.js
> +}
Add a semicolon here.

2021-06-09 16:01 UTC, aljonpineda commented on portfolio/src/main/webapp/app.js
> +const winningScoreSelect = document.querySelector("#playTo")
Add a semicolon here.

2021-06-09 16:01 UTC, aljonpineda commented on portfolio/src/main/webapp/app.js
> +})
Add a semicolon here.

2021-06-09 16:01 UTC, aljonpineda commented on portfolio/src/main/webapp/app.js
> +resetButton.addEventListener('click', reset)
Add a semicolon here.

2021-06-09 16:01 UTC, aljonpineda commented on portfolio/src/main/webapp/index.html
> +                        </header> -->
If these lines aren't needed anymore, go ahead and remove them so that the file only contains used code. In the event that you need to revert to using this code, GitHub keeps a history that you can look up.

2021-06-09 16:01 UTC, aljonpineda commented on portfolio/src/main/webapp/script.js
> +        const res = await axios.get("https://icanhazdadjoke.com/", config)
Add a semicolon to each of these two lines.

2021-06-09 16:01 UTC, aljonpineda commented on portfolio/src/main/webapp/script.js
> +})
Add a semicolon to each of these two lines.

2021-06-09 16:01 UTC, aljonpineda commented on portfolio/src/main/webapp/script.js
> +})
Add a semicolon to each of these two lines.

2021-06-09 16:01 UTC, aljonpineda commented on portfolio/src/main/webapp/app.js
> +})
Add a semicolon to each of these two lines.

2021-06-09 16:01 UTC, aljonpineda commented on portfolio/src/main/webapp/app.js
> +})
Add a semicolon to each of these two lines.

2021-06-09 16:01 UTC, aljonpineda commented on portfolio/src/main/webapp/scorekeeper.html
> +    </header>
The header looks like it can be reused across multiple pages. You don't have to make any changes now, but if you're interested, there are ways to make a reusable component so that any changes you make only need to be done in one place.

2021-06-09 22:37 UTC, temiloluwa-hub commented on portfolio/src/main/webapp/scorekeeper.html
> +    </header>
Interesting. I'll check that out.

2021-06-11 14:34 UTC, aljonpineda approved these changes
Great! You actually don't need semicolons at the end of functions. They're only necessary when you declare a variable, assign a value to a variable, call a function, etc. 

I recommend that you rename the `script2.js` to something more meaningful just so that we can easily remember what kind of functionality it provides.

2021-06-13 19:30 UTC, merged